### ISSUE TITLE
ESI à Bruxelles

### ISSUE THREAD

**Issue by npettiaux** [ronnix/stages#4]
L'école supérieure d'informatique à Bruxelles (http://heb.be/esi) forme des analystes-programmeurs et des administrateurs systèmes en 3 ans et un plan de stages de 15 semaines, soit près de 4 mois, fait partie de la formation. Voir http://www.heb.be/esi/stages_fr.htm. Je suis disponible pour toute demande d'information complémentaire.

**Comment by ronnix** [comment]
Merci !
